### ISSUE TITLE
Failed build with GHC 8.6.3

### ISSUE THREAD

**Issue by r-zip** [Yuras/pdf-toolbox#41]
First of all, thanks for your work.

Apologies if I'm doing something really wrong—I'm a Haskell newbie.

I'm trying to compile my project with `stack build`, and I've added `pdf-toolbox` to the stack.yaml file as follows:

```
extra-deps:
  - github: Yuras/pdf-toolbox
    commit: stable
    subdirs:
      - core
```

I have also added it to the dependencies in package.yaml:
```
```
